swagger: "2.0"

info:
  version: "1.0"
  title: "project-structure-proposal"
  description: "project-structure-proposal"
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /hello-world:
    get:
      summary: Hello world
      description: Hello world
      responses:
        200:
          description: Hello world
